name: Note AI Crawler

on:
  schedule:
    # Run at 00:00 UTC every day (09:00 JST)
    - cron: '0 0 * * *'
  workflow_dispatch:  # Manual trigger

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run crawler
      run: python note_ai_crawler.py
      
    - name: Commit and push if there are changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add output/
        git diff --quiet && git diff --staged --quiet || git commit -m "Update AI article data [automated]"
        git push